"""
Tests for the pre-submit positions gate (``scripts/tools/positions_gate.py``) and
the ``positions_meta.json`` sidecar read in ``util.load_vis_dataset``.

The gate is numpy/scipy only; PyAutoLens is used here only as the oracle for the
ray tracing and the light centre, and for the ``load_vis_dataset`` contract.
Synthetic image sets are generated by solving the lens equation with the gate's
own tracer (which the first test pins to ``al.Tracer``), so they are exact.
"""

import csv
import json
import shutil
import sys
from pathlib import Path

import numpy as np
import pytest
from scipy.optimize import least_squares

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "scripts" / "tools"))

import positions_gate as gate  # noqa: E402

FIXTURES = Path(__file__).parent / "fixtures" / "positions_gate"
EXEMPLARS = {
    "Tile102008208RA0607685059647DECNEG0644176039388": "drop",
    "Tile102014702RA0131539972904DECNEG0557431062995": "review",
    "Tile102012028RA0853629092626DECNEG0587974678810": "drop",
    "Tile102015993RA0419770151744DECNEG0538603861556": "drop",
    "Tile102014701RA0126141761821DECNEG0553233945871": "drop",
}

EXAMPLE_SAMPLE = "q1_walsmley"
EXAMPLE_DATASET = "102018665_NEG570040238507752998"
EXAMPLE_PATH = PROJECT_ROOT / "dataset" / EXAMPLE_SAMPLE / EXAMPLE_DATASET
TMP_SAMPLE = "_pytest_positions_gate"

CENTRE = (0.12, -0.07)
QUAD_PARAMS = (1.2, 0.15, 0.05, 0.04, -0.03)
QUAD_SOURCE = (0.03, 0.05)


# ---------------------------------------------------------------------------
# Synthetic image sets
# ---------------------------------------------------------------------------


def solve_images(params, source, centre=(0.0, 0.0), extent=3.0, n=25):
    """All image-plane solutions of the lens equation for a point source."""
    sols = []
    for y0 in np.linspace(-extent, extent, n):
        for x0 in np.linspace(-extent, extent, n):
            res = least_squares(
                lambda t: gate.source_positions(t[None, :], params)[0] - np.asarray(source),
                [y0, x0],
                xtol=1e-14,
                ftol=1e-14,
            )
            if np.hypot(*res.fun) < 1e-9 and np.hypot(*res.x) > 0.05:
                if all(np.hypot(*(res.x - s)) > 1e-4 for s in sols):
                    sols.append(res.x)
    return np.array(sols) + np.asarray(centre)


@pytest.fixture(scope="module")
def quad():
    images = solve_images(QUAD_PARAMS, QUAD_SOURCE, centre=CENTRE)
    assert len(images) == 4
    return images


def sis_double(theta_e=1.0, beta=0.3, centre=CENTRE):
    """Analytic SIS double: images at r = theta_E +/- beta on either side of the lens."""
    return np.array(
        [[centre[0], centre[1] + theta_e + beta], [centre[0], centre[1] - (theta_e - beta)]]
    )


# ---------------------------------------------------------------------------
# Tracer and light centre against PyAutoLens
# ---------------------------------------------------------------------------


def test_max_separation_matches_pyautolens_tracer():
    import autolens as al

    pos = np.array([[1.1, 0.3], [-0.8, -0.6], [0.2, -1.2], [-0.4, 1.0]])
    for p in ((1.1, 0.2, -0.1, 0.05, 0.12), (0.7, -0.3, 0.25, -0.2, 0.1), (2.5, 0.0, 0.0, 0.0, 0.0)):
        te, e0, e1, g1, g2 = p
        lens = al.Galaxy(
            redshift=0.5,
            mass=al.mp.Isothermal(centre=CENTRE, ell_comps=(e0, e1), einstein_radius=te),
        )
        field = al.MassField(redshift=0.5, shear=al.mp.ExternalShear(gamma_1=g1, gamma_2=g2))
        tracer = al.Tracer(galaxies=[lens, al.Galaxy(redshift=1.0)], fields=[field])
        traced = np.asarray(tracer.traced_grid_2d_list_from(grid=al.Grid2DIrregular(values=pos))[-1])
        d = np.hypot(traced[:, None, 0] - traced[None, :, 0], traced[:, None, 1] - traced[None, :, 1])
        assert gate.max_separation(pos - np.array(CENTRE), p) == pytest.approx(d.max(), abs=1e-9)


def test_brightest_sub_pixel_centre_matches_autoarray():
    import autolens as al

    rng = np.random.default_rng(3)
    for centre in ((0.0, 0.0), (0.35, -0.42), (-1.1, 0.8)):
        img = rng.uniform(0.1, 1.0, (40, 40))
        arr = al.Array2D.no_mask(values=img, pixel_scales=0.1)
        expected = arr.brightest_sub_pixel_coordinate_in_region_from(
            region=(centre[0] - 0.3, centre[0] + 0.3, centre[1] - 0.3, centre[1] + 0.3),
            box_size=2,
        )
        got = gate.brightest_sub_pixel_centre(img, 0.1, centre)
        assert got == pytest.approx(tuple(expected), abs=1e-9)


# ---------------------------------------------------------------------------
# Quick fit and full gate on synthetic sets
# ---------------------------------------------------------------------------


def test_sis_double_traces_and_keeps_at_the_floor():
    meta = gate.gate_positions(sis_double(), CENTRE)
    assert meta["s_min"] < 1e-3
    assert meta["status"] == "keep"
    assert meta["threshold"] == 0.3
    assert meta["dropped"] == []
    assert len(meta["positions_used"]) == 2


def test_sie_quad_traces_and_keeps_at_the_floor(quad):
    # A seed tracing the set to < EASY (0.02") is accepted without the minimax
    # polish (prototype behaviour): s_min is exact only to that level here.
    fit = gate.quick_fit(quad, CENTRE)
    assert fit["s_min"] < gate.EASY
    meta = gate.gate_positions(quad, CENTRE)
    assert meta["status"] == "keep"
    assert meta["threshold"] == 0.3
    assert len(meta["positions_used"]) == 4


def test_nucleus_image_is_cut(quad):
    pos = np.vstack([quad, [CENTRE[0] + 0.1, CENTRE[1]]])
    meta = gate.gate_positions(pos, CENTRE)
    assert meta["dropped"] == [
        dict(index=4, y=round(CENTRE[0] + 0.1, 4), x=round(CENTRE[1], 4), reason="central_cut")
    ]
    assert meta["status"] == "drop"
    assert meta["threshold"] == 0.3
    assert len(meta["positions_used"]) == 4


def test_image_just_outside_the_cut_is_not_cut():
    kept, cut = gate.central_cut([[0.0, 0.16], [0.0, 0.14], [1.0, 1.0]], (0.0, 0.0))
    assert kept == [0, 2] and cut == [1]


def test_spurious_image_is_dropped_exactly(quad):
    pos = np.vstack([quad[:2], [[CENTRE[0] + 2.6, CENTRE[1] + 1.9]], quad[2:]])
    meta = gate.gate_positions(pos, CENTRE)
    assert meta["s_min_all"] > 0.2
    assert [d["index"] for d in meta["dropped"]] == [2]
    assert meta["dropped"][0]["reason"].startswith("outlier_")
    assert meta["status"] == "drop"
    assert meta["s_min"] < gate.EASY
    assert meta["threshold"] == 0.3
    assert len(meta["positions_used"]) == 4


def test_untraceable_pair_goes_to_review():
    # Two images on the same side of the lens along one ray cannot be traced.
    pos = np.array([[CENTRE[0], CENTRE[1] + 1.0], [CENTRE[0], CENTRE[1] + 3.0]])
    meta = gate.gate_positions(pos, CENTRE)
    assert meta["status"] == "review"
    assert meta["review_reason"] == "n2_fail"
    assert meta["dropped"] == []


def test_fewer_than_two_survivors_turns_the_penalty_off():
    pos = np.array([[CENTRE[0] + 0.05, CENTRE[1]], [CENTRE[0], CENTRE[1] + 1.3]])
    meta = gate.gate_positions(pos, CENTRE)
    assert meta["status"] == "n_lt_2"
    assert meta["threshold"] is None
    assert len(meta["positions_used"]) == 1
    assert meta["dropped"][0]["reason"] == "central_cut"


# ---------------------------------------------------------------------------
# Outlier-drop decision rules (leave-one-out fits injected)
# ---------------------------------------------------------------------------


def _loo(s, J):
    return [dict(s_min=a, J=b, params=[0.0] * 5, params_J=[0.0] * 5) for a, b in zip(s, J)]


# Radii from the centre: 1.0, 1.1, 1.2, 1.3 (none inner, none outer).
RING = np.array([[1.0, 0.0], [0.0, 1.1], [-1.2, 0.0], [0.0, -1.3]])
FAIL = dict(s_min=0.8, J=300.0)


def test_single_candidate_is_dropped():
    d = gate.outlier_drop(RING, (0, 0), FAIL, _loo([0.9, 0.05, 0.9, 0.9], [9, 9, 9, 9]))
    assert (d["action"], d["index"], d["reason"]) == ("drop", 1, "unique")
    assert d["s_final"] == 0.05


def test_cost_margin_picks_the_lowest_J():
    d = gate.outlier_drop(RING, (0, 0), FAIL, _loo([0.01, 0.02, 0.9, 0.9], [8.0, 3.9, 9, 9]))
    assert (d["action"], d["index"], d["reason"]) == ("drop", 1, "J")


def test_similar_J_nearest_inner_image_is_dropped():
    pos = RING.copy()
    pos[2] = [-0.25, 0.0]
    d = gate.outlier_drop(pos, (0, 0), FAIL, _loo([0.01, 0.02, 0.03, 0.9], [5, 6, 7, 9]))
    assert (d["action"], d["index"], d["reason"]) == ("drop", 2, "geom_inner")


def test_similar_J_outer_neighbour_is_dropped():
    pos = RING.copy()
    pos[0] = [3.0, 0.0]
    d = gate.outlier_drop(pos, (0, 0), FAIL, _loo([0.01, 0.9, 0.9, 0.02], [5, 9, 9, 6]))
    assert (d["action"], d["index"], d["reason"]) == ("drop", 0, "geom_outer")


def test_similar_J_without_geometry_goes_to_review():
    d = gate.outlier_drop(RING, (0, 0), FAIL, _loo([0.01, 0.02, 0.9, 0.9], [5, 6, 9, 9]))
    assert (d["action"], d["reason"]) == ("review", "ambiguous")


def test_no_candidate_goes_to_review():
    d = gate.outlier_drop(RING, (0, 0), FAIL, _loo([0.5, 0.6, 0.7, 0.9], [5, 6, 7, 9]))
    assert (d["action"], d["reason"]) == ("review", "no_single_drop")


def test_traceable_set_is_kept_without_leave_one_out():
    d = gate.outlier_drop(RING, (0, 0), dict(s_min=0.2, J=1.0))
    assert d["action"] == "keep" and d["loo"] is None


def test_plausibility_flag():
    fit = dict(s_min=0.05, J=20.0)
    assert gate.plausibility_flag(fit, _loo([0] * 4, [9.9, 15, 16, 17])) == 0
    assert gate.plausibility_flag(fit, _loo([0] * 4, [10.1, 15, 16, 17])) is None  # dJ < 10
    assert gate.plausibility_flag(fit, _loo([0] * 4, [9.0, 12.0, 16, 17])) is None  # not unique


# ---------------------------------------------------------------------------
# Threshold clamp
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "s, T, over",
    [
        (0.0, 0.3, False),
        (0.149, 0.3, False),
        (0.15, 0.3, False),
        (0.2, 0.4, False),
        (0.25, 0.5, False),
        (0.26, 0.5, True),
        (1.2, 0.5, True),
    ],
)
def test_threshold_clamp(s, T, over):
    assert gate.threshold_from(s) == (pytest.approx(T), over)


# ---------------------------------------------------------------------------
# The five output_locked exemplar tiles
# ---------------------------------------------------------------------------


def _fixture_centre(tile):
    return json.loads((FIXTURES / tile / "light_centre.json").read_text())["light_centre"]


@pytest.fixture(scope="module")
def exemplar_metas(tmp_path_factory):
    root = tmp_path_factory.mktemp("exemplars")
    metas = {}
    for tile in EXEMPLARS:
        shutil.copytree(FIXTURES / tile, root / tile)
        metas[tile] = gate.gate_tile(root / tile, light_centre=_fixture_centre(tile))
    return root, metas


@pytest.mark.parametrize("tile", list(EXEMPLARS))
def test_exemplar_verdicts(exemplar_metas, tile):
    _, metas = exemplar_metas
    meta = metas[tile]
    assert meta["status"] == EXEMPLARS[tile]
    if EXEMPLARS[tile] == "review":
        assert meta["review_reason"] == "no_single_drop"
    else:
        assert meta["threshold"] == 0.3
        assert len(meta["dropped"]) == 1
        assert meta["s_min"] <= 0.15


def test_exemplar_drops_match_the_prototype(exemplar_metas):
    # research/B_sample_results.csv (2026-09-24): drop index and full-set s_min.
    _, metas = exemplar_metas
    expected = {
        "Tile102008208RA0607685059647DECNEG0644176039388": (2, "outlier_J", 1.1825),
        "Tile102012028RA0853629092626DECNEG0587974678810": (2, "outlier_unique", 1.1794),
        "Tile102015993RA0419770151744DECNEG0538603861556": (3, "outlier_unique", 1.1560),
        # The nucleus image (r = 0.098") the prototype dropped on cost is cut first here.
        "Tile102014701RA0126141761821DECNEG0553233945871": (3, "central_cut", None),
    }
    for tile, (index, reason, s_all) in expected.items():
        meta = metas[tile]
        assert (meta["dropped"][0]["index"], meta["dropped"][0]["reason"]) == (index, reason)
        if s_all is not None:
            assert meta["s_min_all"] == pytest.approx(s_all, abs=0.01)


def test_gate_tile_writes_the_sidecar_and_leaves_positions_raw(exemplar_metas):
    root, metas = exemplar_metas
    for tile in EXEMPLARS:
        assert (root / tile / "positions.json").read_bytes() == (
            FIXTURES / tile / "positions.json"
        ).read_bytes()
        on_disk = json.loads((root / tile / gate.META_NAME).read_text())
        assert on_disk["status"] == metas[tile]["status"]
        assert on_disk["version"] == gate.GATE_VERSION


def test_gate_batch_holds_review_tiles_back(exemplar_metas, tmp_path):
    root, _ = exemplar_metas
    # No positions.json: no sidecar, submitted as before.
    (root / "TileNoPositions").mkdir(exist_ok=True)
    gate.gate_batch(root, out_csv=tmp_path / "positions_review.csv")
    submit = (tmp_path / "positions_submit.txt").read_text().split()
    review = "Tile102014702RA0131539972904DECNEG0557431062995"
    assert review not in submit
    assert "TileNoPositions" in submit
    assert len(submit) == 5
    rows = list(csv.DictReader(open(tmp_path / "positions_review.csv")))
    assert [(r["tile"], r["status"], r["review_reason"]) for r in rows] == [
        (review, "review", "no_single_drop")
    ]
    gate.gate_batch(root, out_csv=tmp_path / "positions_review.csv", include_review=True)
    assert review in (tmp_path / "positions_submit.txt").read_text().split()


def test_cli_help_runs():
    with pytest.raises(SystemExit) as exc:
        gate.main(["--help"])
    assert exc.value.code == 0


# ---------------------------------------------------------------------------
# util.py: positions_meta.json read and fallback
# ---------------------------------------------------------------------------


def _write_meta(path, **kw):
    meta = dict(status="drop", positions_used=[[1.0, 0.5], [-0.9, -0.4]], threshold=0.34)
    meta.update(kw)
    (Path(path) / gate.META_NAME).write_text(json.dumps(meta))


def test_util_meta_absent_means_default_behaviour(tmp_path):
    import util

    assert util.positions_likelihood_list_from_meta(tmp_path) == (False, None)


def test_util_meta_uses_positions_and_threshold(tmp_path):
    import util

    _write_meta(tmp_path)
    found, lh = util.positions_likelihood_list_from_meta(tmp_path)
    assert found and len(lh) == 1
    assert lh[0].threshold == pytest.approx(0.34)
    assert np.asarray(lh[0].positions).tolist() == [[1.0, 0.5], [-0.9, -0.4]]


def test_util_meta_n_lt_2_turns_the_penalty_off(tmp_path):
    import util

    _write_meta(tmp_path, status="n_lt_2", positions_used=[[1.0, 0.5]], threshold=None)
    assert util.positions_likelihood_list_from_meta(tmp_path) == (True, None)


@pytest.fixture(scope="module")
def tmp_sample():
    path = PROJECT_ROOT / "dataset" / TMP_SAMPLE
    shutil.rmtree(path, ignore_errors=True)
    path.mkdir(parents=True)
    try:
        yield path
    finally:
        shutil.rmtree(path, ignore_errors=True)


def _dataset_with_positions(sample_path, name):
    d = sample_path / name
    d.mkdir(parents=True, exist_ok=True)
    shutil.copy(EXAMPLE_PATH / f"{EXAMPLE_DATASET}.fits", d / f"{name}.fits")
    shutil.copy(EXAMPLE_PATH / "info.json", d / "info.json")
    shutil.copy(
        FIXTURES / "Tile102012028RA0853629092626DECNEG0587974678810" / "positions.json",
        d / "positions.json",
    )
    return d


def test_load_vis_dataset_reads_the_sidecar_and_falls_back(tmp_sample):
    import util

    d = _dataset_with_positions(tmp_sample, "with_positions")
    raw = util.load_vis_dataset(dataset_name="with_positions", sample_name=TMP_SAMPLE)
    assert raw.positions_likelihood_list[0].threshold == 0.2
    assert len(raw.positions_likelihood_list[0].positions) == 4

    # The gate's light centre is the loader's dataset_centre.
    assert gate.light_centre_from_dataset(d) == pytest.approx(tuple(raw.dataset_centre), abs=1e-9)

    _write_meta(d)
    gated = util.load_vis_dataset(dataset_name="with_positions", sample_name=TMP_SAMPLE)
    assert gated.positions_likelihood_list[0].threshold == pytest.approx(0.34)
    assert len(gated.positions_likelihood_list[0].positions) == 2

    _write_meta(d, status="n_lt_2", positions_used=[], threshold=None)
    off = util.load_vis_dataset(dataset_name="with_positions", sample_name=TMP_SAMPLE)
    assert off.positions_likelihood_list is None
